// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified-0]
	_ = x[NilLiteral-1]
	_ = x[BoolLiteral-2]
	_ = x[IntLiteral-3]
	_ = x[DoubleLiteral-4]
	_ = x[StrLiteral-5]
	_ = x[Plus-6]
	_ = x[Minus-7]
	_ = x[Times-8]
	_ = x[Div-9]
	_ = x[Modulo-10]
	_ = x[Equal-11]
	_ = x[NotEqual-12]
	_ = x[LessThan-13]
	_ = x[LessEq-14]
	_ = x[GreaterThan-15]
	_ = x[GreaterEq-16]
	_ = x[LogicalAnd-17]
	_ = x[LogicalOr-18]
	_ = x[BitwiseAnd-19]
	_ = x[BitwiseOr-20]
	_ = x[BitwiseXor-21]
	_ = x[ShiftLeft-22]
	_ = x[ShiftRight-23]
	_ = x[Dot-24]
	_ = x[Not-25]
	_ = x[Complement-26]
	_ = x[Merge-27]
	_ = x[Comma-28]
	_ = x[LeftParen-29]
	_ = x[RightParen-30]
	_ = x[LeftBrace-31]
	_ = x[RightBrace-32]
	_ = x[LeftSquare-33]
	_ = x[RightSquare-34]
	_ = x[Colon-35]
	_ = x[Ident-36]
	_ = x[Func-37]
	_ = x[Let-38]
	_ = x[Template-39]
	_ = x[If-40]
	_ = x[Then-41]
	_ = x[Else-42]
	_ = x[EndOfInput-43]
}

const _TokenType_name = "UnspecifiedNilLiteralBoolLiteralIntLiteralDoubleLiteralStrLiteralPlusMinusTimesDivModuloEqualNotEqualLessThanLessEqGreaterThanGreaterEqLogicalAndLogicalOrBitwiseAndBitwiseOrBitwiseXorShiftLeftShiftRightDotNotComplementMergeCommaLeftParenRightParenLeftBraceRightBraceLeftSquareRightSquareColonIdentFuncLetTemplateIfThenElseEndOfInput"

var _TokenType_index = [...]uint16{0, 11, 21, 32, 42, 55, 65, 69, 74, 79, 82, 88, 93, 101, 109, 115, 126, 135, 145, 154, 164, 173, 183, 192, 202, 205, 208, 218, 223, 228, 237, 247, 256, 266, 276, 287, 292, 297, 301, 304, 312, 314, 318, 322, 332}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
